# Generated by Django 3.0.7 on 2020-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200706_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/main_page')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
