# Generated by Django 3.0.5 on 2020-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200706_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='slug',
            field=models.CharField(default=1, max_length=250, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hello',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
