# Generated by Django 3.0.5 on 2020-07-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200715_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team_consist',
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(default=1, upload_to='static/img/persons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Team'),
        ),
    ]
