# Generated by Django 3.0.5 on 2020-07-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_image_subgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SubgroupImage',
        ),
    ]
