# Generated by Django 3.0.5 on 2020-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200715_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.CharField(max_length=255, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='person',
            name='team_role',
            field=models.CharField(max_length=50, null=True, verbose_name='Командная роль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
