# Generated by Django 3.0.5 on 2020-07-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200715_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Имя команды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Team'),
        ),
    ]
