# Generated by Django 3.0.5 on 2020-07-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200715_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='static/img/persons'),
        ),
    ]
