# Generated by Django 3.0.5 on 2020-07-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200715_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hello',
            old_name='img',
            new_name='suck',
        ),
    ]
