# Generated by Django 3.0.5 on 2020-07-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200715_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hello',
            old_name='suck',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='suck',
        ),
    ]
