# Generated by Django 3.0.7 on 2020-07-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(help_text='for instance, "catalog/mechanisms/meo"', max_length=200, null=True, unique=True, verbose_name='url'),
        ),
    ]
