# Generated by Django 3.0.7 on 2020-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='name',
            field=models.CharField(default=9999, max_length=250),
            preserve_default=False,
        ),
    ]
