# Generated by Django 3.0.5 on 2020-07-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200715_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='suck',
            new_name='img',
        ),
    ]
