# Generated by Django 3.0.7 on 2020-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_subgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='name',
        ),
    ]
