# Generated by Django 3.0.7 on 2020-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_remove_subgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgroup',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
