# Generated by Django 3.0.7 on 2020-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20200723_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='slug',
            field=models.CharField(help_text='for instance, "catalog/mechanisms/meo"', max_length=200, null=True, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
