# Generated by Django 3.0.7 on 2020-07-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20200723_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='slug',
        ),
    ]
