# Generated by Django 3.0.7 on 2020-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20200723_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='main_page'),
        ),
        migrations.AlterField(
            model_name='subgroupimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mechanisms'),
        ),
    ]
