# Generated by Django 3.0.7 on 2020-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200724_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mechanisms'),
        ),
    ]
