# Generated by Django 3.0.7 on 2020-07-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_subgroup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='image',
        ),
    ]
