# Generated by Django 3.0.7 on 2020-07-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_subgroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroupimage',
            name='image',
            field=models.ImageField(null=True, upload_to='mechanisms'),
        ),
        migrations.AlterField(
            model_name='subgroupimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Subgroup'),
        ),
    ]
