# Generated by Django 3.0.7 on 2020-07-26 08:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20200725_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='subgroup',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
