# Generated by Django 3.0.5 on 2020-07-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20200726_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Categories'),
        ),
    ]
