# Generated by Django 3.0.5 on 2020-07-29 09:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20200728_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.CharField(help_text='for instance, "40 or 25000"', max_length=200, null=True, unique=True, verbose_name='url')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Subgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='subgroupimage',
            old_name='post',
            new_name='page',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='mechanisms')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
