# Generated by Django 3.1.4 on 2021-01-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20210117_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
    ]
