# Generated by Django 3.0.7 on 2020-07-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20200729_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='product',
            name='parental_slug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Categories'),
            preserve_default=False,
        ),
    ]
