# Generated by Django 3.1.1 on 2021-01-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20210117_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
    ]
