# Generated by Django 3.0.7 on 2020-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20200729_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(help_text='for instance, "mechanisms/meo"', max_length=200, null=True, unique=True, verbose_name='url'),
        ),
    ]
