# Generated by Django 3.0.5 on 2020-07-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='preview_img',
        ),
    ]
