# Generated by Django 3.0.5 on 2020-07-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20200729_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview_img',
            new_name='img',
        ),
    ]
