# Generated by Django 3.0.5 on 2020-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20200729_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_product',
            field=models.SlugField(default=1, help_text='for instance, "40 or 6_3"', verbose_name='url'),
            preserve_default=False,
        ),
    ]
