# Generated by Django 3.0.5 on 2020-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20200729_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='mechanisms_preview', verbose_name='Изображение для ссылки'),
            preserve_default=False,
        ),
    ]
