# Generated by Django 3.1.7 on 2021-04-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20210404_0957'),
        ('mainapp', '0044_auto_20210407_1044'),
    ]

    operations = [
    ]
