# Generated by Django 3.0.7 on 2020-07-30 14:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20200730_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='description',
        ),
        migrations.AddField(
            model_name='categories',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(blank=True, help_text='for instance, "mechanisms/meo"', max_length=200, null=True, unique=True, verbose_name='url'),
        ),
    ]
