# Generated by Django 3.0.7 on 2020-07-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20200730_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroupimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Categories'),
        ),
        migrations.DeleteModel(
            name='Subgroup',
        ),
    ]
