# Generated by Django 3.0.7 on 2020-07-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20200730_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Group',
        ),
    ]
