# Generated by Django 3.0.5 on 2020-07-31 10:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20200730_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mechanisms_preview', verbose_name='Изображение для ссылки'),
        ),
    ]
