# Generated by Django 3.0.5 on 2020-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='group',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция на странице'),
            preserve_default=False,
        ),
    ]
