# Generated by Django 3.0.5 on 2020-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_auto_20200802_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='Позиция на странице'),
        ),
        migrations.AlterField(
            model_name='product',
            name='href_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
