# Generated by Django 3.0.5 on 2020-08-03 10:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_auto_20200803_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
