# Generated by Django 3.0.5 on 2020-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_auto_20200803_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pic_of_hat',
            field=models.ImageField(blank=True, help_text='size: 1920x500px', null=True, upload_to='pic_of_hat'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название на странице группы'),
        ),
    ]
