# Generated by Django 3.0.5 on 2020-08-06 10:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_auto_20200805_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='for instance, "64/10-0,25-IICT4-05"', verbose_name='url')),
                ('titile', models.CharField(max_length=250)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
            options={
                'ordering': ['parent'],
            },
        ),
        migrations.DeleteModel(
            name='SubgroupImage',
        ),
    ]
