# Generated by Django 3.0.5 on 2020-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0064_auto_20200806_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
