# Generated by Django 3.0.7 on 2020-08-06 21:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0066_auto_20200806_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mod_table',
            field=tinymce.models.HTMLField(default=12334344, help_text="Указание идентификатора обязательно id = 'MOD'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
