# Generated by Django 3.0.5 on 2020-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20200806_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='h1',
            field=models.CharField(default=1243, max_length=250),
            preserve_default=False,
        ),
    ]
