# Generated by Django 3.0.7 on 2020-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0070_auto_20200808_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
