# Generated by Django 3.0.5 on 2020-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_auto_20200808_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='h1',
        ),
        migrations.AddField(
            model_name='product',
            name='h1_mod',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
