# Generated by Django 3.0.7 on 2020-08-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0074_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
