# Generated by Django 3.0.7 on 2020-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_modification_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='conventional_designation',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
