# Generated by Django 3.0.7 on 2020-08-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_modification_conventional_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.TextField(blank=True, help_text='bootstrap icons in svg tags', max_length=1000, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
