# Generated by Django 3.0.7 on 2020-08-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_auto_20200823_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='conventional_designation',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='quantity',
        ),
    ]
