# Generated by Django 3.0.7 on 2020-08-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0077_productdocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, help_text='bootstrap icons in svg tags', max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productdocs',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.DocIcon'),
        ),
    ]
