# Generated by Django 3.1 on 2020-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_auto_20200822_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocs',
            name='file',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
