# Generated by Django 3.0.7 on 2020-08-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_auto_20200822_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocs',
            name='file',
            field=models.FileField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
