# Generated by Django 3.1 on 2020-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0080_auto_20200822_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocs',
            name='file',
            field=models.FileField(default=12, upload_to='docs'),
            preserve_default=False,
        ),
    ]
